GAME = 'flappy-bird'
INPUT_SIZE = 84
INPUT_CHANNEL = 3
ACTIONS = 3
GAMMA = 0.99  # decay rate of past observations
OBSERVE = 50000.  # timesteps to observe before training
EXPLORE = 2000000.  # frames over which to anneal epsilon
FINAL_EPSILON = 0.0001  # final value of epsilon
INITIAL_EPSILON = 0.1  # starting value of epsilon
REPLAY_MEMORY = 50000  # number of previous transitions to remember
BATCH_SIZE = 32  # size of minibatch
FRAME_PER_ACTION = 1
